export const ATTENDANCE = {
  SELECT_EVENTS: "Select events",
  SEE_PROJECT_DETAILS: "See project details",
  NAME: "Name",
  SELF_CHECK_IN: "Self check-in",
  INDIVIDUAL_QUESTION: "Individual question",
  PULL_REQUEST: "Pull request",
  CHECK: "Check",
  TOTAL_PARTICIPANTS: "Total participants",
  PEOPLE: "people",
  ATTEND: "Attend",
  ABSENT: "Absent",
  WITHDRAW: "Withdraw",
  SUBMITTED: "Submitted",
  I_AM_HERE: "I'm here",
  ATTENDED: "Attended",
  ATTENDANCE: "Attendance",
  ACTIONS: "Actions",
  LATE: "Late",
  UNCHECKED: "Unchecked",
  CREATED_PR: "Created PR",
  NOT_CREATED_PR: "Not created PR",
};
