export const EVENTS = {
    UPCOMINGEVENTS: "Upcoming events",
    PASEDEVENTS: "Past events",
    ADDNEWEVENT: "Add a new event",
    CREATENEWEVENT: "Create a new event",
    ADDNEWEVENT_DECRIPTION: "You can add new events here.",
    TITLE: "Title",
    DATE: "Date",
    DESCRIPTION: "Description",
    LINK: "Link",
    ADD: "Add",
    CANCEL: "Cancel",
    DIALOG_DESCRIPTION: "Let's create a new event.",
    DIALOG_TITLE: "Create new event",
    CREATE: "Create",
}