export const GROUP = {
  MEMBERS: "Members",
  JOIN: "Join",
  GOTO: "Go to dashboard",
  CREATE_BUTTON: "Create Group",
  GROUP_TITLE: "Create new group",
  GROUP_DESCRIPTION: "Create a new group to organize your events",
  TITLE: "Title",
  DESCRIPTION: "Description",
  MAX_PARTICIPANTS: "Max participants",
  ATTENDANCE_DEDUCTION: "Attendance deduction",
  ASSIGNMENT_DEDUCTION: "Assignment deduction",
  CREATE: "Create",
  JOIN_TITLE: "Join Group",
  JOIN_DESCRIPTION: "Are you sure you want to join this group?",
  MANAGE_GROUP: "Manage Group",
  GROUP_PAGE_SUB_TITLE: "Create, join, and manage your groups.",
  JOIN_GROUP: "Join a Group",
  SEARCH_BTUTTON: "Browse",
  YOUR_GROUP: "Your Group",
  MUST_BE_LOGGED_IN: "You must be logged in to view this page.",
};
