export const GROUP = {
  MEMBERS: "Members",
  JOIN: "Join",
  GOTO: "Go to dashboard",
  CREATE_BUTTON: "Create Group",
  GROUP_TITLE: "Create new group",
  GROUP_DESCRIPTION: "Create a new group to organize your events",
  TITLE: "Title",
  DESCRIPTION: "Description",
  MAX_PARTICIPANTS: "Max participants",
  ATTENDANCE_DEDUCTION: "Attendance deduction",
  ASSIGNMENT_DEDUCTION: "Assignment deduction",
  CREATE: "Create",
  JOIN_TITLE: "Join Group",
  JOIN_DESCRIPTION: "Are you sure you want to join this group?",
  CHECK_OUT_GROUP: "Participating Group",
  EXPLORE_NEW_GROUP: "Explore New Groups to Join",
  JOIN_PAGE_SUB_TITLE: "Explore and join a new group to study",
  GROUP_PAGE_SUB_TITLE: "Check out groups you are participating and go to the group dashboard. New group can be created!",
  JOIN_GROUP: "Join a New Group",
  SEARCH_BTUTTON: "Browse",
  ADMIN_GROUP: "Groups as an admin",
  MEMBER_GROUP: "Groups as a member",
  MUST_BE_LOGGED_IN: "You must be logged in to view this page.",
  TOTAL_DEPOSITS: "Total Deposits",
  INITIAL_DEDUCTION: "Initial Deduction",
  MARKED_AS_ATTENDED: "Marked as Attended",
  MARKED_AS_PRESENT: "Marked as Present",
  MARKED_AS_ABSENT: "Marked as Absent",
  MARKED_AS_LATE: "Marked as Late",
};
