export const SETTINGS_CONSTANTS = {
  SETTINGS_HEADER_TITLE: "Account Settings",
  SETTINGS_SUB_TITLE: "Manage your account settings and preferences.",
  CARD_TITLE: "Personal Information",
  SETTINGS_NAME: "Name",
  SETTINGS_SAVE: "Save",
  SETTINGS_DELETE_ACCOUNT: "Delete Account",
  ALERT_TITLE: "Are you sure you want to delete your account?",
  ALERT_DESCRIPTION:
    "This will immediately log you out of your account and you will not be able to log in again.",
  ALERT_CANCEL: "Cancel",
  MANAGEMENT_GROUPS: "Management Groups",
  MANAGEMENT_GROUPS_DESCRIPTION:
    "Delete or leave groups you no longer participate in.",
  GROUP_ADMIN: "Group as an admin",
  GROUP_MEMBER: "Group as a member",
  PROFILE_DESCRIPTION: "Manage your account details and preferences.",
  DANGER_ZONE: "Danger Zone",
  DANGER_DESCRIPTION:
    "Actions in danger zone can't be undone. Please proceed with caution.",
  PROFILE_SETTINGS: "Profile Settings",
  NO_ADMIN_GROUPS: "You are not an admin of any groups.",
  NO_MEMBER_GROUPS: "You are not a member of any groups.",
  SETTINGS_DELETE_GROUP: "Delete Group",
  SETTINGS_QUIT_GROUP: "Leave Group",
  CONFIRM_DELETE_TITLE: "Delete Group",
  CONFIRM_DELETE_DESCRIPTION: "Are you sure you want to delete this group? This action cannot be undone.",
  CONFIRM_QUIT_TITLE: "Leave Group",
  CONFIRM_QUIT_DESCRIPTION: "Are you sure you want to leave this group?",
  DIALOG_CONFIRM: "Confirm",
  DIALOG_CANCEL: "Cancel",
  TOAST_GROUP_DELETED: "Group has been successfully deleted.",
  TOAST_GROUP_LEFT: "You have successfully left the group.",
  TOAST_ERROR_DELETE: "Failed to delete the group. Please try again.",
  TOAST_ERROR_QUIT: "Failed to leave the group. Please try again.",
  ARIA_ADMIN_GROUPS: "List of groups you administer",
  ARIA_MEMBER_GROUPS: "List of groups you're a member of",
};
