export const SETTINGS_CONSTANTS = {
    SETTINGS_HEADER_TITLE: "Account Settings",
    SETTINGS_SUB_TITLE:"Manage your account settings and preferences.",
    CARD_TITLE: "Personal Information",
    SETTINGS_NAME: "Name",
    SETTINGS_SAVE: "Save Changes",
    SETTINGS_DELETE_ACCOUNT: "Delete Account",
    ALERT_TITLE: "Are you sure you want to delete your account?",
    ALERT_DESCRIPTION: "This action cannot be undone. This will permanently delete your account and remove your data from our servers.",
    ALERT_CANCEL: "Cancel",
    MANAGEMENT_GROUPS: "Management Groups",
    MANAGEMENT_GROUPS_DESCRIPTION: "Delete or leave groups you no longer participate in.",
    GROUP_ADMIN: "Group as an admin",
    GROUP_MEMBER: "Group as a member",
}