export const CONSTANTS = {
  TITLE: "Week 8 – Online Mock Interview",
  DATE: "April 11, 2024",
  NAME: "Name",
  EMAIL: "Email",
  LEVEL: "Level",
  DEPOSIT: "Deposit",
  STUDENT_NAME: "Chul Su",
  STUDENT_EMAIL: "ChulSu@abc.com",
  STUDENT_LEVEL: "Novice",
  ASSIGNMENTS_TITLE: "Assignments",
  ASSIGNMENT_1: "417. Pacific Atlantic Water Flow",
  ASSIGNMENT_2: "Individual",
  UPCOMING_EVENTS_TITLE: "Upcoming Events",
  EVENT_1_TITLE: "Week 2 – Online Mock Interview",
  EVENT_1_DATE: "April 04, 2024",
  EVENT_2_TITLE: "Week 3 – Online Mock Interview",
  EVENT_2_DATE: "April 11, 2024",
  CHOOSE_DATE_TITLE: "Choose date",
  CHOOSE_DATE_DESCRIPTION: "You can see all details based on a date",
  VIEW_TIPS_BUTTON: "View Tips",
  SEE_PROJECT_DETAILS: "See project details",
};
