export const SUMMARY= {
  NO_UPCOMING_EVENTS: "No upcoming events, Let's create a new one.",
  TITLE: "Summary",
  TABLE_TITLE: "All users",
  NAME: "Name",
  EMAIL: "Email",
  LEVEL: "Level",
  PR: "PR",
  ASSIGNMENT: "Assignment",
  ATTENDANCE: "Attendance",
  ZOOM_LINK: "Zoom Link",
  DEPOSIT: "Deposit",
  STUDENT_NAME: "Chul Su",
  STUDENT_EMAIL: "ChulSu@abc.com",
  STUDENT_LEVEL: "Novice",
  ASSIGNMENTS_TITLE: "Assignments",
  ASSIGNMENT_1: "417. Pacific Atlantic Water Flow",
  ASSIGNMENT_2: "Individual",
  ASSIGNMENT_SUBMISSION_TITLE: "Assignment Submission",
  ASSIGNMENT_TITLE: "Title",
  ASSIGNMENT_TITLE_DESCRIPTION: "Enter the title of question",
  ASSIGNMENT_CONTENT: "Content",
  ASSIGNMENT_CONTENT_DESCRIPTION: "Enter the answer",
  SELECT_EVENT_TITLE: "Select Event",
  UPCOMING_EVENTS_TITLE: "Upcoming Events",
  PROJECT_DETAILS: "See Project Details",
  EVENT_1_TITLE: "Week 2 – Online Mock Interview",
  EVENT_1_DATE: "April 04, 2024",
  EVENT_2_TITLE: "Week 3 – Online Mock Interview",
  EVENT_2_DATE: "April 11, 2024",
  CHOOSE_DATE_TITLE: "Choose date",
  CHOOSE_DATE_DESCRIPTION: "You can see all details based on a date",
  VIEW_TIPS_BUTTON: "View Tips",
  SEE_PROJECT_DETAILS: "See project details",
  BUTTON_SUBMIT:"Submit",
  BUTTON_CHECK: "Check",
  BUTTON_JOIN: "Join",
  BUTTON_VIEW: "View",
  EVENT_TITLE: "Selected event",
  NO_EVENT: "No event",

};
